import Head from "next/head";
import { Inter } from "next/font/google";
import { Text } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-8 min-h-[100vh] flex justify-center">
        <Text
          fontSize="5xl"
          className="font-extrabold max-w-[650px]  bg-gradient-to-r from-indigo-500 via-purple-500 text-transparent to-pink-500 bg-clip-text "
        >
          Hello from, Next + TS + Tailwind + Chakra Template
        </Text>
      </main>
    </>
  );
}
